"""
PromptForge AI - Abstract LLM Provider Interface.

Defines the universal contract for all external and local AI providers:
Gemini, OpenAI, Anthropic, Ollama, and Mock.
"""

from abc import ABC, abstractmethod
from typing import Any

from pydantic import BaseModel, Field

from app.config.constants import ProviderType


class LLMMessage(BaseModel):
    """Standardized chat message payload."""

    role: str = Field(..., description="system, user, assistant")
    content: str = Field(..., description="Message text")


class LLMResponse(BaseModel):
    """Standardized response from any LLM provider."""

    text: str = Field(..., description="Generated text content")
    model: str = Field(..., description="Model identifier that generated the response")
    provider: ProviderType = Field(..., description="Provider hosting the model")
    input_tokens: int = Field(default=0, description="Tokens in user/system prompt")
    output_tokens: int = Field(default=0, description="Tokens generated by model")
    latency_ms: int = Field(default=0, description="Execution latency in milliseconds")
    estimated_cost_usd: float = Field(default=0.0, description="Cost calculated from model matrix")
    finish_reason: str = Field(default="stop", description="stop, length, content_filter")
    raw_response: dict[str, Any] | None = Field(default=None, description="Original vendor payload")
    fallback_used: bool = Field(default=False, description="Whether circuit breaker fallback was activated")


class AbstractLLMProvider(ABC):
    """Universal interface for LLM execution, streaming, and embeddings."""

    @property
    @abstractmethod
    def provider_type(self) -> ProviderType:
        """Returns the enum type of this provider."""

    @abstractmethod
    async def generate(
        self,
        prompt: str,
        system_prompt: str | None = None,
        model: str | None = None,
        temperature: float = 0.7,
        max_tokens: int = 1500,
        stop_sequences: list[str] | None = None,
    ) -> LLMResponse:
        """Executes a single prompt completion."""

    @abstractmethod
    async def embed(
        self,
        text: str,
        model: str | None = None,
    ) -> list[float]:
        """Generates a dense vector embedding for semantic search."""

    @abstractmethod
    async def is_available(self) -> bool:
        """Checks if credentials and network endpoints are operational."""
